In [1]:
'''
1. Write a function to create a 2-D List/Array with random integers between 0 to 100. This function should take two arguments -
   numberOfRows and numberOfColumns and return 2D list.
2. Write a function to sort the 2-D list based on column index keeping the rows intact. This function should take two arguments 
   - 2D list created above and column Index and return sorted 2D list.
'''

'\n1. Write a function to create a 2-D List/Array with random integers between 0 to 100. This function should take two arguments -\n   numberOfRows and numberOfColumns and return 2D list.\n2. Write a function to sort the 2-D list based on column index keeping the rows intact. This function should take two arguments \n   - 2D list created above and column Index and return sorted 2D list.\n'

In [2]:
import random
import numpy as np


In [14]:
#Q1

def generate(numberofRows, numberofColumns):
    arr = []
    for i in range(numberofRows):
        col = []
        for i in range(numberofColumns):
            col.append(random.randint(0,100))
        arr.append(col)
    return arr

numberofRows = int(input(""))
numberofColumns = int(input(""))

arr = generate(numberofRows,numberofColumns)
arr = np.array(arr)
print(arr)


5
6
[[31 66  8  7 92  4]
 [40 26 88 60 85 89]
 [57 85 39 78 33 83]
 [57 29 16 36  2  6]
 [25 17 55 82 17 78]]


In [15]:
#Q2

col_idx = int(input(""))
def sort_col_idx(arr, col_idx):
    sortedArr = arr[arr[:,col_idx].argsort()]
    print("Array sorted by column number :",col_idx)
    print(sortedArr)   
    
sort_col_idx(arr, col_idx)



2
Array sorted by column number : 2
[[31 66  8  7 92  4]
 [57 29 16 36  2  6]
 [57 85 39 78 33 83]
 [25 17 55 82 17 78]
 [40 26 88 60 85 89]]
